import { Injectable } from '@angular/core';
import { IndustryField, IndustryFieldCode, Country, PaymentTerm, CompanyCode, LegalForm, Title, Salutation } from '../interfaces/lists';

/**
 * ListService contains all lists
 */
@Injectable({
  providedIn: 'root'
})
export class ListService {

  legalFormsOrganization: LegalForm [] = [
    { details: 'AG', code: "01"},
    { details: 'eG E. Genossenschaft', code: "09" },
    { details: 'eV Eingetr. Verein', code: "10" },
    { details: 'GmbH', code: "02" },
    { details: 'GmbH&Co.KG', code: "04" },
    { details: 'KG', code: "06" },
    { details: 'KGAA', code: "05" },
    { details: 'OHG', code: "07" },
    { details: 'S.E.', code: "03" },
    { details: 'Staatl. Einrichtung', code: "18" },
    { details: 'Stiftung', code: "17" },
    { details: 'UG', code: "08" },
    { details: 'UG&Co. KG', code: "20" },
    { details: 'Sonstiges', code: "99" },
    { details: 'GbR Ges. bürg. Rechts', code: "13" },
    { details: 'Privat', code: "19" },
  ];

  legalFormsPerson: LegalForm[] = [
    { details: 'Eingetragener Kfm.', code: "11" },
    { details: 'Einzelunternehmen', code: "16" },
    { details: 'Freier Beruf', code: "15" },
    { details: 'Gewerbebetrieb', code: "14" },
    { details: 'Landwirt', code: "16" },
    { details: 'Privat', code: "19" },
  ];

  titles: Title[] = [
    { details: 'Dr.', code: "0001" },
    { details: 'Prof.', code: "0002" },
    { details: 'Prof. Dr.', code: "0003" },
    { details: 'B.A.', code: "0004" },
    { details: 'MBA', code: "0005" },
    { details: 'Ph.D.', code: "0006" },
  ]

  salutationsOrganization: Salutation[] = [
    { details: 'Firma', code: "0003" },
    { details: 'Frau und Frau', code: "0006" },
    { details: 'Frau und Herrn', code: "0005" },
    { details: 'Herrn und Frau', code: "0004" },
    { details: 'Herrn und Herrn', code: "0007" },
  ]

  salutationsPerson: Salutation[] = [
    { details: 'Herr', code: "0002" },
    { details: 'Frau', code: "0001" },
  ]

  paymentTermsDebit: PaymentTerm[] = [
    { code: '0000', details: 'B000/000/000 fällig sofort netto' },
    { code: '0300', details: 'D003/000/000: fällig in 3 Tagen netto' },
    { code: '0800', details: 'B008/000/000 fällig in 8 Tagen netto' },
    { code: '0820', details: 'B030/008/020 8 Tage mit  2,0 % Skto' },
    { code: '0830', details: 'B030/008/030 8 Tage mit  3,0 % Skto' },
    { code: '1000', details: 'B010/000/000 fällig in 10 Tagen netto' },
    { code: '1020', details: 'B030/010/020 30 Tg - 10 Tg 2,0% Skto' },
    { code: '1030', details: 'B030/010/030 fällig in 30 Tg - 10 Tg 3,0% Skonto' },
    { code: '1040', details: 'D030/010/040 fällig in 30 Tg - 10 Tg 4,0% Skonto' },
    { code: '1100', details: 'D011/000/000: fällig in 11 Tagen netto' },
    { code: '1400', details: 'B014/000/000: Beleg-Datum + 14 Tage netto' },
    { code: '1420', details: 'B030/014/020 30 Tage netto 14 Tage mit 2 % Skonto' },
    { code: '1430', details: 'B030/014/030 14 Tage mit 3,0 % Skto' },
    { code: '1500', details: 'B015/000/000: fällig in 15 Tagen netto' },
    { code: '1530', details: 'D030/015/030 fällig in 30 Tg - 15 Tg 3,0% Skonto' },
    { code: '1600', details: 'D016/000/000: fällig in 16 Tagen netto' },
    { code: '1800', details: 'D018/000/000: fällig in 18 Tagen netto' },
    { code: '1T20', details: 'D020/010/020 20 Tg - 10 Tg 2,0% Skto' },
    { code: '2100', details: 'D021/000/000: fällig in 21 Tagen netto' },
    { code: '2120', details: 'B030/021/020 30 Tg. nett + 21 Tg.  mit  2,0 % Skto' },
    { code: '213A', details: 'B030/021/030 30 Tg. netto + 21 Tage  3,0 % Skto' },
    { code: '213B', details: 'D045/021/030 45 Tg. netto + 21 Tage  3,0 % Skto' },
    { code: '2140', details: 'B000/021/040 Beleg-Datum + 21 Tage mit  4,0 % Skto' },
    { code: '214A', details: 'D045/021/040 45 Tg. netto + 21 Tage  4,0 % Skto' },
    { code: '2500', details: 'B025/000/000: fällig in 25 Tagen netto' },
    { code: '280A', details: 'D028/000/000: fällig in 28 Tagen netto' },
    { code: '3000', details: 'B030/000/000 fällig in 30 Tagen netto' },
    { code: '4200', details: 'D042/000/000: fällig in 42 Tagen netto' },
    { code: '4500', details: 'B045/000/000: Beleg-Datum + 45 Tage netto' },
    { code: '453A', details: 'D060/045/030 60 Tage netto 45 Tage mit 3 % Skonto' },
    { code: '6000', details: 'D060/000/000: fällig in 60 Tagen netto' },
    { code: '9000', details: 'B090/000/000 fällig in 90 Tagen netto' },
    { code: '9999', details: 'FiBu-Erfassung mit vorgegebenen Zahlbar-Daten' },
    { code: 'ABAR', details: 'Barzahlung bei Abholung' },
    { code: 'ABRZ', details: 'Barzahlung bei Zustellung' },
    { code: 'AVOR', details: 'Vorauskasse' },
  ];

  paymentTermsCredit: PaymentTerm[] = [
    { code: '0000', details: 'B000/000/000 fällig sofort netto' },
    { code: '0500', details: 'K005/000/000: Beleg-Datum + 5 Tage netto' },
    { code: '0700', details: 'K007/000/000: Beleg-Datum + 7 Tage netto' },
    { code: '0800', details: 'B008/000/000 fällig in 8 Tagen netto' },
    { code: '0820', details: 'B030/008/020 8 Tage mit  2,0 % Skto' },
    { code: '0830', details: 'B030/008/030 8 Tage mit  3,0 % Skto' },
    { code: '1000', details: 'B010/000/000 fällig in 10 Tagen netto' },
    { code: '1020', details: 'B030/010/020 30 Tg - 10 Tg 2,0% Skto' },
    { code: '1030', details: 'B030/010/030 fällig in 30 Tg - 10 Tg 3,0% Skonto' },
    { code: '1400', details: 'B014/000/000: Beleg-Datum + 14 Tage netto' },
    { code: '1420', details: 'B030/014/020 30 Tage netto 14 Tage mit 2 % Skonto' },
    { code: '1430', details: 'B030/014/030 14 Tage mit 3,0 % Skto' },
    { code: '1500', details: 'B015/000/000: fällig in 15 Tagen netto' },
    { code: '2000', details: 'K020/000/000: Beleg-Datum + 20 Tage netto' },
    { code: '2050', details: 'K000/020/005: Beleg-Datum + 20 Tg. m.5,0 % Skto.' },
    { code: '2120', details: 'B030/021/020 30 Tg. nett + 21 Tg.  mit  2,0 % Skto' },
    { code: '2130', details: 'K000/021/030 Beleg-Datum + 21 Tage mit  3,0 % Skto' },
    { code: '213A', details: 'B030/021/030 30 Tg. netto + 21 Tage  3,0 % Skto' },
    { code: '2140', details: 'B000/021/040 Beleg-Datum + 21 Tage mit  4,0 % Skto' },
    { code: '2500', details: 'B025/000/000: fällig in 25 Tagen netto' },
    { code: '2800', details: 'K028/000/000: Beleg-Datum + 28 Tage netto' },
    { code: '3000', details: 'B030/000/000 fällig in 30 Tagen netto' },
    { code: '300A', details: 'K030/000/000: Beleg-Datum + 30 Tage netto' },
    { code: '3040', details: 'K000/030/040 Beleg-Datum + 30 Tage mit  4,0 % Skto' },
    { code: '4040', details: 'K000/040/004: Beleg-Datum + 40 Tg. m.4,0 % Skto.' },
    { code: '4500', details: 'B045/000/000: Beleg-Datum + 45 Tage netto' },
    { code: '4530', details: 'K000/045/003: Beleg-Datum + 45 Tg. m.3,0 % Skto.' },
    { code: '4540', details: 'K000/045/004: Beleg-Datum + 45 Tg. m.4,0 % Skto.' },
    { code: '9000', details: 'B090/000/000 fällig in 90 Tagen netto' },
    { code: '9999', details: 'FiBu-Erfassung mit vorgegebenen Zahlbar-Daten' },
  ];

  industryFields: IndustryField[] = [
    { code: 'A1', details: 'Acker- und Planzenbau' },
    { code: 'A3', details: 'Tierhaltung' },
    { code: 'A5', details: 'sonstige Landwirtschaft' },
    { code: 'A7', details: 'Forstwirtschaft' },
    { code: 'A9', details: 'Fischerei und Aquakultur' },
    { code: 'B1', details: 'Bergbau' },
    { code: 'C1', details: 'Verarbeitendes Gewerbe' },
    { code: 'D1', details: 'Energieversorgung' },
    { code: 'E1', details: 'Wasserversorgung' },
    { code: 'E5', details: 'Entsorgung Abfall/Abwasser' },
    { code: 'F1', details: 'Baugewerbe(Hochbau)' },
    { code: 'F3', details: 'Baugewerbe(Tiefbau)' },
    { code: 'F5', details: 'sonst.Baugewerbe' },
    { code: 'G1', details: 'Handel KFZ' },
    { code: 'G4', details: 'Großhandel' },
    { code: 'G7', details: 'Einzelhandel' },
    { code: 'H1', details: 'Verkehr & Personenbeförderung' },
    { code: 'I1', details: 'Gastgewerbe' },
    { code: 'J1', details: 'Information und Kommunikation (IT)' },
    { code: 'K1', details: 'Finanzdienstleistungen' },
    { code: 'L1', details: 'Grundstücks- und Wohnungswesen' },
    { code: 'M1', details: 'freiberufliche, wissenschaftl., techn. Dienstleistungen' },
    { code: 'N1', details: 'sonst. wirtschaftlichen Dienstleistungen' },
    { code: 'O1', details: 'öffentl. Verwalt., Verteidigung; Sozialversicherung' },
    { code: 'P1', details: 'Erziehung und Unterricht' },
    { code: 'Q1', details: 'Gesundheits- und Sozialwesen' },
    { code: 'R1', details: 'Kunst, Unterhaltung und Erholung' },
    { code: 'S1', details: 'Erbringung von sonstigen Dienstleistungen' },
    { code: 'T1', details: 'private Haushalte' },
    { code: 'U1', details: 'Exterritoriale Organisationen und Körperschaften' }
  ];

  industryFieldCodeA1: IndustryFieldCode[] = [
    { code: '0111', details: 'Anbau von Getreide (ohne Reis), Hülsenfrüchten und Ölsaaten' },
    { code: '0112', details: 'Anbau von Reis' },
    { code: '0113', details: 'Anbau von Gemüse und Melonen sowie Wurzeln und Knollen' },
    { code: '0114', details: 'Anbau von Zuckerrohr' },
    { code: '0115', details: 'Anbau von Tabak' },
    { code: '0116', details: 'Anbau von Faserpflanzen' },
    { code: '0119', details: 'Anbau von sonstigen einjährigen Pflanzen' },
    { code: '0121', details: 'Anbau von Wein- und Tafeltrauben' },
    { code: '0122', details: 'Anbau von tropischen und subtropischen Früchten' },
    { code: '0123', details: 'Anbau von Zitrusfrüchten' },
    { code: '0124', details: 'Anbau von Kern- und Steinobst' },
    { code: '0125', details: 'Anbau von sonstigem Obst und Nüssen' },
    { code: '0126', details: 'Anbau von ölhaltigen Früchten' },
    { code: '0127', details: 'Anbau von Pflanzen zur Herstellung von Getränken' },
    { code: '0128', details: 'Anbau von Gewürzpflanzen, Pflanzen für aromatische, narkotische und pharmazeutische Zwecke' },
    { code: '0129', details: 'Anbau sonstiger mehrjähriger Pflanzen' },
    { code: '0130', details: 'Betrieb von Baumschulen, sowie Anbau von Pflanzen zu Vermehrungszwecken' },
  ];

  industryFieldCodeA3: IndustryFieldCode[] = [
    { code: '0141', details: 'Haltung von Milchkühen' },
    { code: '0142', details: 'Haltung von Pferden und Eseln' },
    { code: '0143', details: 'Haltung von Kamelen' },
    { code: '0144', details: 'Haltung von Schafen und Ziegen' },
    { code: '0145', details: 'Haltung von Schweinen' },
    { code: '0146', details: 'Haltung von Geflügel' },
    { code: '0149', details: 'Sonstige Tierhaltung' },
  ];

  industryFieldCodeA5: IndustryFieldCode[] = [
    { code: '0150', details: 'Gemischte Landwirtschaft' },
    { code: '0161', details: 'Erbringung von landwirtschaftlichen Dienstleistungen für den Pflanzenbau' },
    { code: '0163', details: 'Nach der Ernte anfallende Tätigkeiten in der pflanzlichen Erzeugung' },
    { code: '0164', details: 'Saatgutaufbereitung' },
    { code: '0170', details: 'Jagd, Fallenstellerei und damit verbundene Tätigkeiten' },
  ];

  industryFieldCodeA7: IndustryFieldCode[] = [
    { code: '0210', details: 'Forstwirtschaft' },
    { code: '0220', details: 'Holzeinschlag' },
    { code: '0230', details: 'Sammeln von wild wachsenden Produkten (ohne Holz)' },
    { code: '0240', details: 'Erbringung von Dienstleistungen für Forstwirtschaft und Holzeinschlag' },
  ];

  industryFieldCodeA9: IndustryFieldCode[] = [
    { code: '0311', details: 'Meeresfischerei' },
    { code: '0312', details: 'Süßwasserfischerei' },
    { code: '0321', details: 'Meeresaquakultur' },
    { code: '0322', details: 'Süßwasseraquakultur' },
  ];

  industryFieldCodeB1: IndustryFieldCode[] = [
    { code: '0510', details: 'Steinkohlenbergbau' },
    { code: '0520', details: 'Braunkohlenbergbau' },
    { code: '0610', details: 'Gewinnung von Erdöl' },
    { code: '0620', details: 'Gewinnung von Erdgas' },
    { code: '0710', details: 'Eisenerzbergbau' },
    { code: '0721', details: 'Bergbau auf Uran- und Thoriumerze' },
    { code: '0729', details: 'Sonstiger NE-Metallerzbergbau' },
    { code: '0810', details: 'Gewinnung von Naturwerksteinen und Natursteinen, Kalk- und Gipsstein, Kreide und Schiefer' },
    { code: '0891', details: 'Bergbau auf chemische und Düngemittelminerale' },
    { code: '0892', details: 'Torfgewinnung' },
    { code: '0893', details: 'Gewinnung von Salz' },
    { code: '0899', details: 'Gewinnung von Steinen und Erden a. n. g.' },
    { code: '0910', details: 'Erbringung von Dienstleistungen für die Gewinnung von Erdöl und Erdgas' },
    { code: '0990', details: 'Erbringung von Dienstleistungen für den sonstigen Bergbau und die Gewinnung von Steinen und Erden' },
  ];

  industryFieldCodeC1: IndustryFieldCode[] = [
    { code: '1010', details: 'Schlachten (ohne Schlachten von Geflügel)' },
    { code: '1020', details: 'Fischverarbeitung' },
    { code: '1030', details: 'Kartoffelverarbeitung' },
    { code: '1040', details: 'Herstellung von Ölen und Fetten (ohne Margarine u. ä. Nahrungsfette)' },
    { code: '1050', details: 'Milchverarbeitung (ohne Herstellung von Speiseeis)' },
    { code: '1061', details: 'Mahl- und Schälmühlen' },
    { code: '1062', details: 'Herstellung von Stärke und Stärkeerzeugnissen' },
    { code: '1071', details: 'Herstellung von Backwaren (ohne Dauerbackwaren)' },
    { code: '1072', details: 'Herstellung von Zucker' },
    { code: '1073', details: 'Herstellung von Süßwaren (ohne Dauerbackwaren)' },
    { code: '1074', details: 'Herstellung von Teigwaren' },
    { code: '1075', details: 'Herstellung von Fertiggerichten' },
    { code: '1079', details: 'Verarbeitung von Kaffee und Tee, Herstellung von Kaffee-Ersatz' },
    { code: '1080', details: 'Herstellung von Futtermitteln für Nutztiere' },
    { code: '1101', details: 'Herstellung von Spirituosen' },
    { code: '1102', details: 'Herstellung von Traubenwein' },
    { code: '1103', details: 'Herstellung von Bier' },
    { code: '1104', details: 'Herstellung von Erfrischungsgetränken; Gewinnung natürlicher Mineralwässer' },
    { code: '1200', details: 'Tabakverarbeitung' },
    { code: '1311', details: 'Spinnstoffaufbereitung und Spinnerei' },
    { code: '1312', details: 'Weberei' },
    { code: '1313', details: 'Veredlung von Textilien und Bekleidung' },
    { code: '1391', details: 'Herstellung von gewirktem und gestricktem Stoff' },
    { code: '1392', details: 'Herstellung von konfektionierten Textilwaren (ohne Bekleidung)' },
    { code: '1393', details: 'Herstellung von Teppichen' },
    { code: '1394', details: 'Herstellung von Seilerwaren' },
    { code: '1399', details: 'Herstellung von Vliesstoff und Erzeugnissen daraus (ohne Bekleidung)' },
    { code: '1410', details: 'Herstellung von Lederbekleidung' },
    { code: '1420', details: 'Herstellung von Pelzwaren' },
    { code: '1430', details: 'Herstellung von Strumpfwaren' },
    { code: '1511', details: 'Herstellung von Leder und Lederfaserstoff; Zurichtung und Färben von Fellen' },
    { code: '1512', details: 'Lederverarbeitung (ohne Herstellung von Lederbekleidung)' },
    { code: '1520', details: 'Herstellung von Schuhen' },
    { code: '1610', details: 'Säge-, Hobel- und Holzimprägnierwerke' },
    { code: '1621', details: 'Herstellung von Furnier-, Sperrholz-, Holzfaser- und Holzspanplatten' },
    { code: '1622', details: 'Herstellung von Parketttafeln' },
    { code: '1623', details: 'Herstellung von Verpackungsmitteln, Lagerbehältern und Ladungsträgern aus Holz' },
    { code: '1629', details: 'Herstellung von Holzwaren a.n.g, Kork-, Flecht- und Korbwaren (ohne Möbel)' },
    { code: '1701', details: 'Herstellung von Holz- und Zellstoff' },
    { code: '1702', details: 'Herstellung von Wellpapier und -pappe sowie von Verpackungsmitteln aus Papier, Karton und Pappe' },
    { code: '1709', details: 'Herstellung von Haushalts-, Hygiene- und Toilettenartikeln aus Zellstoff, Papier und Pappe' },
    { code: '1811', details: 'Drucken von Zeitungen' },
    { code: '1812', details: 'Druck- und Medienvorstufe' },
    { code: '1820', details: 'Vervielfältigung von bespielten Ton-, Bild- und Datenträgern' },
    { code: '1910', details: 'Kokerei' },
    { code: '1920', details: 'Mineralölverarbeitung' },
    { code: '2011', details: 'Herstellung von Industriegasen' },
    { code: '2012', details: 'Herstellung von Düngemitteln und Stickstoffverbindungen' },
    { code: '2013', details: 'Herstellung von Kunststoffen in Primärformen' },
    { code: '2021', details: 'Herstellung von Schädlingsbekämpfungs-, Pflanzenschutz- und Desinfektionsmitteln' },
    { code: '2022', details: 'Herstellung von Anstrichmitteln, Druckfarben und Kitten' },
    { code: '2023', details: 'Herstellung von Seifen, Wasch-, Reinigungs- und Poliermitteln' },
    { code: '2029', details: 'Herstellung von pyrotechnischen Erzeugnissen' },
    { code: '2030', details: 'Herstellung von Chemiefasern' },
    { code: '2100', details: 'Herstellung von pharmazeutischen Grundstoffen' },
    { code: '2211', details: 'Herstellung und Runderneuerung von Bereifungen' },
    { code: '2219', details: 'Herstellung von sonstigen Gummiwaren' },
    { code: '2220', details: 'Herstellung von Platten, Folien, Schläuchen und Profilen aus Kunststoffen' },
    { code: '2310', details: 'Herstellung von Flachglas' },
    { code: '2391', details: 'Herstellung von feuerfesten keramischen Werkstoffen und Waren' },
    { code: '2392', details: 'Herstellung von keramischen Wand- und Bodenfliesen und -platten' },
    { code: '2393', details: 'Herstellung von keramischen Haushaltswaren und Ziergegenständen' },
    { code: '2394', details: 'Herstellung von Zement' },
    { code: '2395', details: 'Herstellung von Erzeugnissen aus Beton, Zement und Kalksandstein für den Bau' },
    { code: '2396', details: 'Be- und Verarbeitung von Naturwerksteinen und Natursteinen a. n. g.' },
    { code: '2399', details: 'Herstellung von Schleifkörpern und Schleifmitteln auf Unterlage' },
    { code: '2410', details: 'Erzeugung von Roheisen, Stahl und Ferrolegierungen' },
    { code: '2420', details: 'Erzeugung und erste Bearbeitung von Edelmetallen' },
    { code: '2431', details: 'Eisengießereien' },
    { code: '2432', details: 'Leichtmetallgießereien' },
    { code: '2511', details: 'Herstellung von Metallkonstruktionen' },
    { code: '2512', details: 'Herstellung von Heizkörpern und -kesseln für Zentralheizungen' },
    { code: '2513', details: 'Herstellung von Dampfkesseln (ohne Zentralheizungskessel)' },
    { code: '2520', details: 'Herstellung von Waffen und Munition' },
    { code: '2591', details: 'Herstellung von Schmiede-, Press-, Zieh- und Stanzteilen, gewalzten Ringen und pulvermetallurgischen' },
    { code: '2592', details: 'Oberflächenveredlung und Wärmebehandlung' },
    { code: '2593', details: 'Herstellung von Schneidwaren und Bestecken aus unedlen Metallen' },
    { code: '2599', details: 'Herstellung von Fässern, Trommeln, Dosen, Eimern u. ä. Behältern aus Metall' },
    { code: '2610', details: 'Herstellung von elektronischen Bauelementen' },
    { code: '2620', details: 'Herstellung von Datenverarbeitungsgeräten und peripheren Geräten' },
    { code: '2630', details: 'Herstellung von Geräten und Einrichtungen der Telekommunikationstechnik' },
    { code: '2640', details: 'Herstellung von Geräten der Unterhaltungselektronik' },
    { code: '2651', details: 'Herstellung von Mess-, Kontroll-, Navigations- u. ä. Instrumenten und Vorrichtungen' },
    { code: '2652', details: 'Herstellung von Uhren' },
    { code: '2660', details: 'Herstellung von Bestrahlungs- und Elektrotherapiegeräten und elektromedizinischen Geräten' },
    { code: '2670', details: 'Herstellung von optischen und fotografischen Instrumenten und Geräten' },
    { code: '2680', details: 'Herstellung von magnetischen und optischen Datenträgern' },
    { code: '2710', details: 'Herstellung von Elektromotoren, Generatoren und Transformatoren' },
    { code: '2720', details: 'Herstellung von Batterien und Akkumulatoren' },
    { code: '2731', details: 'Herstellung von Glasfaserkabeln' },
    { code: '2732', details: 'Herstellung von sonstigen elektronischen und elektrischen Drähten und Kabeln' },
    { code: '2733', details: 'Herstellung von elektrischem Installationsmaterial' },
    { code: '2740', details: 'Herstellung von elektrischen Lampen und Leuchten' },
    { code: '2750', details: 'Herstellung von elektrischen Haushaltsgeräten' },
    { code: '2790', details: 'Herstellung von sonstigen elektrischen Ausrüstungen und Geräten a. n. g.' },
    { code: '2811', details: 'Herstellung von Verbrennungsmotoren und Turbinen (ohne Motoren für Luft- und Straßenfahrzeuge)' },
    { code: '2812', details: 'Herstellung von hydraulischen und pneumatischen Komponenten und Systemen' },
    { code: '2813', details: 'Herstellung von Pumpen und Kompressoren a. n. g.' },
    { code: '2814', details: 'Herstellung von Lagern, Getrieben, Zahnrädern und Antriebselementen' },
    { code: '2815', details: 'Herstellung von Öfen und Brennern' },
    { code: '2816', details: 'Herstellung von Hebezeugen und Fördermitteln' },
    { code: '2817', details: 'Herstellung von Büromaschinen (ohne Datenverarbeitungsgeräte und periphere Geräte)' },
    { code: '2818', details: 'Herstellung von handgeführten Werkzeugen mit Motorantrieb' },
    { code: '2819', details: 'Herstellung von kälte- und lufttechnischen Erzeugnissen, nicht für den Haushalt' },
    { code: '2821', details: 'Herstellung von land- und forstwirtschaftlichen Maschinen' },
    { code: '2822', details: 'Herstellung von Werkzeugmaschinen für die Metallbearbeitung' },
    { code: '2823', details: 'Herstellung von Maschinen für die Metallerzeugung, von Walzwerkseinrichtungen und Gießmaschinen' },
    { code: '2824', details: 'Herstellung von Bergwerks-, Bau- und Baustoffmaschinen' },
    { code: '2825', details: 'Herstellung von Maschinen für die Nahrungs- und Genussmittelerzeugung und die Tabakverarbeitung' },
    { code: '2826', details: 'Herstellung von Maschinen für die Textil- und Bekleidungsherstellung und die Lederverarbeitung' },
    { code: '2829', details: 'Herstellung von Maschinen für die Papiererzeugung und -verarbeitung' },
    { code: '2910', details: 'Herstellung von Kraftwagen und Kraftwagenmotoren' },
    { code: '2920', details: 'Herstellung von Karosserien, Aufbauten und Anhängern' },
    { code: '2930', details: 'Herstellung elektrischer und elektronischer Ausrüstungsgegenstände für Kraftwagen' },
    { code: '3011', details: 'Schiffbau (ohne Boots- und Yachtbau)' },
    { code: '3012', details: 'Boots- und Yachtbau' },
    { code: '3020', details: 'Schienenfahrzeugbau' },
    { code: '3030', details: 'Luft- und Raumfahrzeugbau' },
    { code: '3040', details: 'Herstellung von militärischen Kampffahrzeugen' },
    { code: '3091', details: 'Herstellung von Krafträdern' },
    { code: '3092', details: 'Herstellung von Fahrrädern sowie von Behindertenfahrzeugen' },
    { code: '3099', details: 'Herstellung von sonstigen Fahrzeugen a. n. g.' },
    { code: '3100', details: 'Herstellung von Büro- und Ladenmöbeln' },
    { code: '3211', details: 'Herstellung von Münzen' },
    { code: '3212', details: 'Herstellung von Fantasieschmuck' },
    { code: '3220', details: 'Herstellung von Musikinstrumenten' },
    { code: '3230', details: 'Herstellung von Sportgeräten' },
    { code: '3240', details: 'Herstellung von Spielwaren' },
    { code: '3250', details: 'Herstellung von medizinischen und zahnmedizinischen Apparaten und Materialien' },
    { code: '3290', details: 'Herstellung von Besen und Bürsten' },
    { code: '3311', details: 'Reparatur von Metallerzeugnissen' },
    { code: '3312', details: 'Reparatur von Maschinen' },
    { code: '3313', details: 'Reparatur von elektronischen und optischen Geräten' },
    { code: '3314', details: 'Reparatur von elektrischen Ausrüstungen' },
    { code: '3315', details: 'Reparatur und Instandhaltung von Schiffen, Booten und Yachten' },
    { code: '3319', details: 'Reparatur von sonstigen Ausrüstungen' },
    { code: '3320', details: 'Installation von Maschinen und Ausrüstungen a. n. g.' },
  ];

  industryFieldCodeD1: IndustryFieldCode[] = [
    { code: '3510', details: 'Elektrizitätserzeugung' },
    { code: '3520', details: 'Gaserzeugung' },
    { code: '3530', details: 'Wärme- und Kälteversorgung' },
  ];

  industryFieldCodeE1: IndustryFieldCode[] = [
    { code: '3600', details: 'Wasserversorgung' },
  ];

  industryFieldCodeE5: IndustryFieldCode[] = [
{ code: '3700', details: 'Abwasserentsorgung' },
{ code: '3811', details: 'Sammlung nicht gefährlicher Abfälle' },
{ code: '3812', details: 'Sammlung gefährlicher Abfälle' },
{ code: '3821', details: 'Behandlung und Beseitigung nicht gefährlicher Abfälle' },
{ code: '3822', details: 'Behandlung und Beseitigung gefährlicher Abfälle' },
{ code: '3830', details: 'Zerlegen von Schiffs- und Fahrzeugwracks und anderen Altwaren' },
{ code: '3900', details: 'Beseitigung von Umweltverschmutzungen und sonstige Entsorgung' },
];

industryFieldCodeF1: IndustryFieldCode[] = [
{ code: '4100', details: 'Erschließung von Grundstücken; Bauträger' },
];

industryFieldCodeF3: IndustryFieldCode[] = [
{ code: '4210', details: 'Bau von Straßen' },
{ code: '4220', details: 'Rohrleitungstiefbau, Brunnenbau und Kläranlagenbau' },
{ code: '4290', details: 'Wasserbau' },
];

industryFieldCodeF5: IndustryFieldCode[] = [
{ code: '4311', details: 'Abbrucharbeiten' },
{ code: '4312', details: 'Vorbereitende Baustellenarbeiten' },
{ code: '4321', details: 'Elektroinstallation' },
{ code: '4322', details: 'Gas-, Wasser-, Heizungs- sowie Lüftungs- und Klimainstallation' },
{ code: '4329', details: 'Sonstige Bauinstallation' },
{ code: '4330', details: 'Anbringen von Stuckaturen, Gipserei und Verputzerei' },
{ code: '4390', details: 'Dachdeckerei und Zimmerei' },
];

industryFieldCodeG1: IndustryFieldCode[] = [
{ code: '4510', details: 'Handel mit Kraftwagen mit einem Gesamtgewicht von 3,5 t oder weniger' },
{ code: '4520', details: 'Instandhaltung und Reparatur von Kraftwagen' },
{ code: '4530', details: 'Großhandel mit Kraftwagenteilen und -zubehör' },
{ code: '4540', details: 'Handel mit Krafträdern, Kraftradteilen und -zubehör; Instandhaltung und Reparatur von Krafträdern' },
];

industryFieldCodeG4: IndustryFieldCode[] = [
{ code: '4610', details: 'Handelsvermittlung von landwirtschaftlichen Grundstoffen, lebenden Tieren, textilen Rohstoffen und H' },
{ code: '4620', details: 'Großhandel mit Getreide, Rohtabak, Saatgut und Futtermitteln' },
{ code: '4630', details: 'Großhandel mit Obst, Gemüse und Kartoffeln' },
{ code: '4641', details: 'Großhandel mit Textilien' },
{ code: '4649', details: 'Großhandel mit Foto- und optischen Erzeugnissen, elektrischen Haushaltsgeräten und Geräten der Unter' },
{ code: '4651', details: 'Großhandel mit Datenverarbeitungsgeräten, peripheren Geräten und Software' },
{ code: '4652', details: 'Großhandel mit elektronischen Bauteilen und Telekommunikationsgeräten' },
{ code: '4653', details: 'Großhandel mit landwirtschaftlichen Maschinen und Geräten' },
{ code: '4659', details: 'Großhandel mit Werkzeugmaschinen' },
{ code: '4661', details: 'Großhandel mit festen Brennstoffen und Mineralölerzeugnissen' },
{ code: '4662', details: 'Großhandel mit Erzen, Metallen und Metallhalbzeug' },
{ code: '4663', details: 'Großhandel mit Holz, Baustoffen, Anstrichmitteln und Sanitärkeramik' },
{ code: '4669', details: 'Großhandel mit chemischen Erzeugnissen' },
{ code: '4690', details: 'Großhandel ohne ausgeprägten Schwerpunkt' },
];

industryFieldCodeG7: IndustryFieldCode[] = [
{ code: '4711', details: 'Einzelhandel mit Waren verschiedener Art, Hauptrichtung Nahrungs- und Genussmittel, Getränke und Tab' },
{ code: '4719', details: 'Sonstiger Einzelhandel mit Waren verschiedener Art' },
{ code: '4721', details: 'Einzelhandel mit Obst, Gemüse und Kartoffeln' },
{ code: '4722', details: 'Einzelhandel mit Getränken' },
{ code: '4723', details: 'Einzelhandel mit Tabakwaren' },
{ code: '4730', details: 'Einzelhandel mit Motorenkraftstoffen (Tankstellen)' },
{ code: '4741', details: 'Einzelhandel mit Datenverarbeitungsgeräten, peripheren Geräten und Software' },
{ code: '4742', details: 'Einzelhandel mit Geräten der Unterhaltungselektronik' },
{ code: '4751', details: 'Einzelhandel mit Textilien' },
{ code: '4752', details: 'Einzelhandel mit Metallwaren, Anstrichmitteln, Bau- und Heimwerkerbedarf' },
{ code: '4753', details: 'Einzelhandel mit Vorhängen, Teppichen, Fußbodenbelägen und Tapeten' },
{ code: '4759', details: 'Einzelhandel mit elektrischen Haushaltsgeräten' },
{ code: '4761', details: 'Einzelhandel mit Büchern' },
{ code: '4762', details: 'Einzelhandel mit bespielten Ton- und Bildträgern' },
{ code: '4763', details: 'Einzelhandel mit Fahrrädern, Sport- und Campingartikeln' },
{ code: '4764', details: 'Einzelhandel mit Spielwaren' },
{ code: '4771', details: 'Einzelhandel mit Bekleidung' },
{ code: '4772', details: 'Apotheken' },
{ code: '4773', details: 'Einzelhandel mit Blumen, Pflanzen, Sämereien, Düngemitteln, zoologischem Bedarf und lebenden Tieren' },
{ code: '4774', details: 'Einzelhandel mit Antiquitäten und Gebrauchtwaren' },
{ code: '4781', details: 'Einzelhandel mit Nahrungs- und Genussmitteln, Getränken und Tabakwaren an Verkaufsständen und auf Mä' },
{ code: '4782', details: 'Einzelhandel mit Textilien, Bekleidung und Schuhen an Verkaufsständen und auf Märkten' },
{ code: '4789', details: 'Einzelhandel mit sonstigen Gütern an Verkaufsständen und auf Märkten' },
{ code: '4791', details: 'Versand- und Internet-Einzelhandel' },
{ code: '4799', details: 'Sonstiger Einzelhandel, nicht in Verkaufsräumen, an Verkaufsständen oder auf Märkten' },
];

industryFieldCodeH1: IndustryFieldCode[] = [
{ code: '4911', details: 'Personenbeförderung im Eisenbahnfernverkehr' },
{ code: '4912', details: 'Güterbeförderung im Eisenbahnverkehr' },
{ code: '4921', details: 'Personenbeförderung im Nahverkehr zu Lande (ohne Taxis)' },
{ code: '4922', details: 'Betrieb von Taxis' },
{ code: '4923', details: 'Güterbeförderung im Straßenverkehr' },
{ code: '4930', details: 'Transport in Rohrfernleitungen' },
{ code: '5011', details: 'Personenbeförderung in der See- und Küstenschifffahrt' },
{ code: '5012', details: 'Güterbeförderung in der See- und Küstenschifffahrt' },
{ code: '5021', details: 'Personenbeförderung in der Binnenschifffahrt' },
{ code: '5022', details: 'Güterbeförderung in der Binnenschifffahrt' },
{ code: '5110', details: 'Personenbeförderung in der Luftfahrt' },
{ code: '5120', details: 'Güterbeförderung in der Luftfahrt' },
{ code: '5210', details: 'Lagerei' },
{ code: '5221', details: 'Erbringung von sonstigen Dienstleistungen für den Landverkehr' },
{ code: '5222', details: 'Erbringung von sonstigen Dienstleistungen für die Schifffahrt' },
{ code: '5223', details: 'Erbringung von sonstigen Dienstleistungen für die Luftfahrt' },
{ code: '5224', details: 'Frachtumschlag' },
{ code: '5229', details: 'Erbringung von sonstigen Dienstleistungen für den Verkehr a. n. g.' },
{ code: '5310', details: 'Postdienste von Universaldienstleistungsanbietern' },
{ code: '5320', details: 'Sonstige Post-, Kurier- und Expressdienste' },
];

industryFieldCodeI1: IndustryFieldCode[] = [
{ code: '5510', details: 'Hotels, Gasthöfe und Pensionen' },
{ code: '5520', details: 'Campingplätze' },
{ code: '5590', details: 'Sonstige Beherbergungsstätten' },
{ code: '5610', details: 'Restaurants, Gaststätten, Imbissstuben, Cafés, Eissalons u. Ä.' },
{ code: '5621', details: 'Event-Caterer' },
{ code: '5629', details: 'Erbringung sonstiger Verpflegungsdienstleistungen' },
{ code: '5630', details: 'Ausschank von Getränken' },
];

industryFieldCodeJ1: IndustryFieldCode[] = [
{ code: '5811', details: 'Verlegen von Büchern' },
{ code: '5812', details: 'Verlegen von Adressbüchern und Verzeichnissen' },
{ code: '5813', details: 'Verlegen von Zeitungen' },
{ code: '5819', details: 'Sonstiges Verlagswesen (ohne Software)' },
{ code: '5820', details: 'Verlegen von Computerspielen' },
{ code: '5911', details: 'Herstellung von Filmen, Videofilmen und Fernsehprogrammen' },
{ code: '5912', details: 'Nachbearbeitung und sonstige Filmtechnik' },
{ code: '5913', details: 'Filmverleih und -vertrieb (ohne Videotheken)' },
{ code: '5914', details: 'Kinos' },
{ code: '5920', details: 'Tonstudios; Herstellung von Hörfunkbeiträgen; Verlegen von bespielten Tonträgern und Musikalien' },
{ code: '6010', details: 'Hörfunkveranstalter' },
{ code: '6020', details: 'Fernsehveranstalter' },
{ code: '6110', details: 'Leitungsgebundene Telekommunikation' },
{ code: '6120', details: 'Drahtlose Telekommunikation' },
{ code: '6130', details: 'Satellitentelekommunikation' },
{ code: '6190', details: 'Sonstige Telekommunikation' },
{ code: '6201', details: 'Programmierungstätigkeiten' },
{ code: '6202', details: 'Erbringung von Beratungsleistungen auf dem Gebiet der Informationstechnologie' },
{ code: '6209', details: 'Erbringung von sonstigen Dienstleistungen der Informationstechnologie' },
{ code: '6311', details: 'Datenverarbeitung, Hosting und damit verbundene Tätigkeiten' },
{ code: '6312', details: 'Webportale' },
{ code: '6391', details: 'Korrespondenz- und Nachrichtenbüros' },
{ code: '6399', details: 'Erbringung von sonstigen Informationsdienstleistungen a. n. g.' },
];

industryFieldCodeK1: IndustryFieldCode[] = [
{ code: '6411', details: 'Zentralbanken' },
{ code: '6419', details: 'Kreditinstitute (ohne Spezialkreditinstitute)' },
{ code: '6420', details: 'Beteiligungsgesellschaften' },
{ code: '6430', details: 'Treuhand- und sonstige Fonds und ähnliche Finanzinstitutionen' },
{ code: '6491', details: 'Institutionen für Finanzierungsleasing' },
{ code: '6492', details: 'Spezialkreditinstitute' },
{ code: '6499', details: 'Sonstige Finanzdienstleistungen a. n. g.' },
{ code: '6511', details: 'Lebensversicherungen' },
{ code: '6512', details: 'Nichtlebensversicherungen' },
{ code: '6520', details: 'Rückversicherungen' },
{ code: '6530', details: 'Pensionskassen und Pensionsfonds' },
{ code: '6611', details: 'Effekten- und Warenbörsen' },
{ code: '6612', details: 'Effekten- und Warenhandel' },
{ code: '6619', details: 'Sonstige mit Finanzdienstleistungen verbundene Tätigkeiten' },
{ code: '6621', details: 'Risiko- und Schadensbewertung' },
{ code: '6622', details: 'Tätigkeit von Versicherungsmaklerinnen und -maklern' },
{ code: '6629', details: 'Sonstige mit Versicherungsdienstleistungen und Pensionskassen verbundene Tätigkeiten' },
{ code: '6630', details: 'Fondsmanagement' },
];

industryFieldCodeL1: IndustryFieldCode[] = [
{ code: '6810', details: 'Kauf und Verkauf von eigenen Grundstücken, Gebäuden und Wohnungen' },
{ code: '6820', details: 'Vermittlung von Grundstücken, Gebäuden und Wohnungen für Dritte' },
];

industryFieldCodeM1: IndustryFieldCode[] = [
{ code: '6910', details: 'Rechtsberatung' },
{ code: '6920', details: 'Wirtschaftsprüfung und Steuerberatung; Buchführung' },
{ code: '7010', details: 'Verwaltung und Führung von Unternehmen und Betrieben' },
{ code: '7020', details: 'Public-Relations-Beratung' },
{ code: '7110', details: 'Architekturbüros' },
{ code: '7120', details: 'Technische, physikalische und chemische Untersuchung' },
{ code: '7210', details: 'Forschung und Entwicklung im Bereich Biotechnologie' },
{ code: '7220', details: 'Forschung und Entwicklung im Bereich Rechts-, Wirtschafts- und Sozialwissenschaften sowie im Bereich' },
{ code: '7310', details: 'Werbeagenturen' },
{ code: '7320', details: 'Markt- und Meinungsforschung' },
{ code: '7410', details: 'Ateliers für Textil-, Schmuck-, Grafik- u. ä. Design' },
{ code: '7420', details: 'Fotografie und Fotolabors' },
{ code: '7490', details: 'Übersetzen und Dolmetschen' },
{ code: '7500', details: 'Veterinärwesen' },
];

industryFieldCodeN1: IndustryFieldCode[] = [
{ code: '7710', details: 'Vermietung von Kraftwagen mit einem Gesamtgewicht von 3,5 t oder weniger' },
{ code: '7721', details: 'Vermietung von Sport- und Freizeitgeräten' },
{ code: '7722', details: 'Videotheken' },
{ code: '7729', details: 'Vermietung von sonstigen Gebrauchsgütern' },
{ code: '7730', details: 'Vermietung von landwirtschaftlichen Maschinen und Geräten' },
{ code: '7740', details: 'Leasing von nichtfinanziellen immateriellen Vermögensgegenständen (ohne Copyrights)' },
{ code: '7810', details: 'Vermittlung von Arbeitskräften' },
{ code: '7820', details: 'Befristete Überlassung von Arbeitskräften' },
{ code: '7830', details: 'Sonstige Überlassung von Arbeitskräften' },
{ code: '7911', details: 'Reisebüros' },
{ code: '7912', details: 'Reiseveranstalter' },
{ code: '7990', details: 'Erbringung sonstiger Reservierungsdienstleistungen' },
{ code: '8010', details: 'Private Wach- und Sicherheitsdienste' },
{ code: '8020', details: 'Sicherheitsdienste mithilfe von Überwachungs- und Alarmsystemen' },
{ code: '8030', details: 'Detekteien' },
{ code: '8110', details: 'Hausmeisterdienste' },
{ code: '8121', details: 'Allgemeine Gebäudereinigung' },
{ code: '8129', details: 'Spezielle Reinigung von Gebäuden und Reinigung von Maschinen' },
{ code: '8130', details: 'Garten- und Landschaftsbau sowie Erbringung von sonstigen gärtnerischen Dienstleistungen' },
{ code: '8211', details: 'Allgemeine Sekretariats- und Schreibdienste' },
{ code: '8219', details: 'Copy-Shops; Dokumentenvorbereitung und Erbringung sonstiger spezieller Sekretariatsdienste' },
{ code: '8220', details: 'Call Centers' },
{ code: '8230', details: 'Messe-, Ausstellungs- und Kongressveranstalter' },
{ code: '8291', details: 'Inkassobüros und Auskunfteien' },
{ code: '8292', details: 'Abfüllen und Verpacken' },
{ code: '8299', details: 'Erbringung sonstiger wirtschaftlicher Dienstleistungen für Unternehmen und Privatpersonen a. n. g.' },
];

industryFieldCodeO1: IndustryFieldCode[] = [
{ code: '8411', details: 'Allgemeine öffentliche Verwaltung' },
{ code: '8412', details: 'Öffentliche Verwaltung auf den Gebieten Gesundheitswesen, Bildung, Kultur und Sozialwesen' },
{ code: '8413', details: 'Wirtschaftsförderung, -ordnung und -aufsicht' },
{ code: '8421', details: 'Auswärtige Angelegenheiten' },
{ code: '8422', details: 'Verteidigung' },
{ code: '8423', details: 'Rechtspflege' },
{ code: '8430', details: 'Sozialversicherung' },
];

industryFieldCodeP1: IndustryFieldCode[] = [
{ code: '8510', details: 'Kindergärten und Vorschulen' },
{ code: '8521', details: 'Allgemein bildende weiterführende Schulen' },
{ code: '8522', details: 'Berufsbildende weiterführende Schulen' },
{ code: '8530', details: 'Post-sekundärer, nicht tertiärer Unterricht' },
{ code: '8541', details: 'Sport- und Freizeitunterricht' },
{ code: '8542', details: 'Kulturunterricht' },
{ code: '8549', details: 'Fahr- und Flugschulen' },
{ code: '8550', details: 'Erbringung von Dienstleistungen für den Unterricht' },
];

industryFieldCodeQ1: IndustryFieldCode[] = [
{ code: '8610', details: 'Krankenhäuser' },
{ code: '8620', details: 'Arztpraxen für Allgemeinmedizin' },
{ code: '8690', details: 'Gesundheitswesen a. n. g.' },
{ code: '8710', details: 'Pflegeheime' },
{ code: '8720', details: 'Stationäre Einrichtungen zur psychosozialen Betreuung, Suchtbekämpfung u. Ä.' },
{ code: '8730', details: 'Altenheime; Alten- und Behindertenwohnheime' },
{ code: '8790', details: 'Sonstige Heime (ohne Erholungs- und Ferienheime)' },
{ code: '8810', details: 'Soziale Betreuung älterer Menschen und Behinderter' },
{ code: '8890', details: 'Tagesbetreuung von Kindern' },
];

industryFieldCodeR1: IndustryFieldCode[] = [
{ code: '9000', details: 'Darstellende Kunst' },
{ code: '9101', details: 'Bibliotheken und Archive' },
{ code: '9102', details: 'Museen' },
{ code: '9103', details: 'Botanische und zoologische Gärten sowie Naturparks' },
{ code: '9200', details: 'Spiel-, Wett- und Lotteriewesen' },
{ code: '9311', details: 'Betrieb von Sportanlagen' },
{ code: '9312', details: 'Sportvereine' },
{ code: '9319', details: 'Erbringung von sonstigen Dienstleistungen des Sports' },
{ code: '9321', details: 'Vergnügungs- und Themenparks' },
{ code: '9329', details: 'Erbringung von Dienstleistungen der Unterhaltung und der Erholung a. n. g.' },
];

industryFieldCodeS1: IndustryFieldCode[] = [
{ code: '9411', details: 'Wirtschafts- und Arbeitgeberverbände' },
{ code: '9412', details: 'Berufsorganisationen' },
{ code: '9420', details: 'Arbeitnehmervereinigungen' },
{ code: '9491', details: 'Kirchliche und sonstige religiöse Vereinigungen' },
{ code: '9492', details: 'Politische Parteien und Vereinigungen' },
{ code: '9499', details: 'Sonstige Interessenvertretungen und Vereinigungen a. n. g.' },
{ code: '9511', details: 'Reparatur von Datenverarbeitungsgeräten und peripheren Geräten' },
{ code: '9512', details: 'Reparatur von Telekommunikationsgeräten' },
{ code: '9521', details: 'Reparatur von Geräten der Unterhaltungselektronik' },
{ code: '9522', details: 'Reparatur von elektrischen Haushaltsgeräten und Gartengeräten' },
{ code: '9523', details: 'Reparatur von Schuhen und Lederwaren' },
{ code: '9524', details: 'Reparatur von Möbeln und Einrichtungsgegenständen' },
{ code: '9529', details: 'Reparatur von Uhren und Schmuck' },
{ code: '9601', details: 'Wäscherei und chemische Reinigung' },
{ code: '9602', details: 'Frisör- und Kosmetiksalons' },
{ code: '9603', details: 'Bestattungswesen' },
{ code: '9609', details: 'Saunas, Solarien, Bäder u. Ä.' },
];

industryFieldCodeT1: IndustryFieldCode[] = [
{ code: '9700', details: 'Private Haushalte mit Hauspersonal' },
];

industryFieldCodeU1: IndustryFieldCode[] = [
{ code: '9810', details: 'Herstellung von Waren durch private Haushalte für den Eigenbedarf ohne ausgeprägten Schwerpunkt' },
{ code: '9820', details: 'Erbringungen von Dienstleistungen durch private Haushalte für den Eigenbedarf ohne ausgeprägten Schw' },
{ code: '9900', details: 'Exterritoriale Organisationen und Körperschaften' },
];

companyCodes: CompanyCode[] = [
  { code: '1100', details: 'BayWa Haustechnik GmbH' },
  { code: '1101', details: 'BayWa Rent GmbH' },
  { code: '1104', details: 'Peter Frey GmbH' },
  { code: '1160', details: 'Bölke Handel GmbH' },
  { code: '1170', details: 'Interlubes GmbH' },
  { code: '1192', details: 'BSV-Staaten GmbH' },
  { code: '9500', details: 'Obst vom Bodensee Vertrieb GmbH' },
];

industryFieldCodes = new Map([
  ['A1', this.industryFieldCodeA1],
  ['A3', this.industryFieldCodeA3],
  ['A5', this.industryFieldCodeA5],
  ['A7', this.industryFieldCodeA7],
  ['A9', this.industryFieldCodeA9],
  ['B1', this.industryFieldCodeB1],
  ['C1', this.industryFieldCodeC1],
  ['D1', this.industryFieldCodeD1],
  ['E1', this.industryFieldCodeE1],
  ['E5', this.industryFieldCodeE5],
  ['F1', this.industryFieldCodeF1],
  ['F3', this.industryFieldCodeF3],
  ['F5', this.industryFieldCodeF5],
  ['G1', this.industryFieldCodeG1],
  ['G4', this.industryFieldCodeG4],
  ['G7', this.industryFieldCodeG7],
  ['H1', this.industryFieldCodeH1],
  ['I1', this.industryFieldCodeI1],
  ['J1', this.industryFieldCodeJ1],
  ['K1', this.industryFieldCodeK1],
  ['L1', this.industryFieldCodeL1],
  ['M1', this.industryFieldCodeM1],
  ['N1', this.industryFieldCodeN1],
  ['O1', this.industryFieldCodeO1],
  ['P1', this.industryFieldCodeP1],
  ['Q1', this.industryFieldCodeQ1],
  ['R1', this.industryFieldCodeR1],
  ['S1', this.industryFieldCodeS1],
  ['T1', this.industryFieldCodeT1],
  ['U1', this.industryFieldCodeU1],
]);


countries: Country[] = [
  { details: 'Andorra', code: 'AD' },
  { details: 'Ver.Arab.Emir.', code: 'AE' },
  { details: 'Afghanistan', code: 'AF' },
  { details: 'Antigua/Barbuda', code: 'AG' },
  { details: 'Anguilla', code: 'AI' },
  { details: 'Albanien', code: 'AL' },
  { details: 'Armenien', code: 'AM' },
  //{ details: ' ', code: 'AN' },
  { details: 'Angola', code: 'AO' },
  { details: 'Antarktis', code: 'AQ' },
  { details: 'Argentinien', code: 'AR' },
  { details: 'Samoa, Amerikan', code: 'AS' },
  { details: 'Österreich', code: 'AT' },
  { details: 'Australien', code: 'AU' },
  { details: 'Aruba', code: 'AW' },
  //{ details: ' ', code: 'AX' },
  { details: 'Aserbaidschan', code: 'AZ' },
  { details: 'Bosnien-Herz.', code: 'BA' },
  { details: 'Barbados', code: 'BB' },
  { details: 'Bangladesch', code: 'BD' },
  { details: 'Belgien', code: 'BE' },
  { details: 'Burkina-Faso', code: 'BF' },
  { details: 'Bulgarien', code: 'BG' },
  { details: 'Bahrain', code: 'BH' },
  { details: 'Burundi', code: 'BI' },
  { details: 'Benin', code: 'BJ' },
  { details: 'Blue', code: 'BL' },
  { details: 'Bermuda', code: 'BM' },
  { details: 'Brunei Drussal.', code: 'BN' },
  { details: 'Bolivien', code: 'BO' },
  { details: 'Bonaire, Saba', code: 'BQ' },
  { details: 'Brasilien', code: 'BR' },
  { details: 'Bahamas', code: 'BS' },
  { details: 'Bhutan', code: 'BT' },
  { details: 'Bouvet Inseln', code: 'BV' },
  { details: 'Botsuana', code: 'BW' },
  { details: 'Belarus', code: 'BY' },
  { details: 'Belize', code: 'BZ' },
  { details: 'Kanada', code: 'CA' },
  { details: 'Kokosinseln', code: 'CC' },
  { details: 'Republik Kongo', code: 'CD' },
  { details: 'Zentralaf. Rep.', code: 'CF' },
  { details: 'Kongo', code: 'CG' },
  { details: 'Schweiz', code: 'CH' },
  { details: 'Elfenbeinküste', code: 'CI' },
  { details: 'Cookinseln', code: 'CK' },
  { details: 'Chile', code: 'CL' },
  { details: 'Kamerun', code: 'CM' },
  { details: 'China', code: 'CN' },
  { details: 'Kolumbien', code: 'CO' },
  { details: 'Costa Rica', code: 'CR' },
  { details: 'Serbien/Monten.', code: 'CS' },
  { details: 'Kuba', code: 'CU' },
  { details: 'Kap Verde', code: 'CV' },
  { details: 'Curaçao', code: 'CW' },
  { details: 'Weihnachtsinsel', code: 'CX' },
  { details: 'Zypern', code: 'CY' },
  { details: 'Tschechische Re', code: 'CZ' },
  { details: 'Deutschland', code: 'DE' },
  { details: 'Dschibuti', code: 'DJ' },
  { details: 'Dänemark', code: 'DK' },
  { details: 'Dominica', code: 'DM' },
  { details: 'Dominik. Rep.', code: 'DO' },
  { details: 'Algerien', code: 'DZ' },
  { details: 'Ecuador', code: 'EC' },
  { details: 'Estland', code: 'EE' },
  { details: 'Ägypten', code: 'EG' },
  { details: 'West Sahara', code: 'EH' },
  { details: 'Eritrea', code: 'ER' },
  { details: 'Spanien', code: 'ES' },
  { details: 'Äthiopien', code: 'ET' },
  { details: 'Europäische U.', code: 'EU' },
  { details: 'Finnland', code: 'FI' },
  { details: 'Fidschi', code: 'FJ' },
  { details: 'Falklandinseln', code: 'FK' },
  { details: 'Mikronesien', code: 'FM' },
  { details: 'Färöer', code: 'FO' },
  { details: 'Frankreich', code: 'FR' },
  { details: 'Gabun', code: 'GA' },
  { details: 'Verein. Königr.', code: 'GB' },
  { details: 'Grenada', code: 'GD' },
  { details: 'Georgien', code: 'GE' },
  { details: 'Französ.Guayana', code: 'GF' },
  { details: 'Gournsey', code: 'GG' },
  { details: 'Ghana', code: 'GH' },
  { details: 'Gibraltar', code: 'GI' },
  { details: 'Grönland', code: 'GL' },
  { details: 'Gambia', code: 'GM' },
  { details: 'Guinea', code: 'GN' },
  { details: 'Guadeloupe', code: 'GP' },
  { details: 'Äquatorialguine', code: 'GQ' },
  { details: 'Griechenland', code: 'GR' },
  { details: 'S. Sandwich Ins', code: 'GS' },
  { details: 'Guatemala', code: 'GT' },
  { details: 'Guam', code: 'GU' },
  { details: 'Guinea-Bissau', code: 'GW' },
  { details: 'Guyana', code: 'GY' },
  { details: 'Hongkong', code: 'HK' },
  { details: 'Heard/McDon.Ins', code: 'HM' },
  { details: 'Honduras', code: 'HN' },
  { details: 'Kroatien', code: 'HR' },
  { details: 'Haiti', code: 'HT' },
  { details: 'Ungarn', code: 'HU' },
  { details: 'Indonesien', code: 'ID' },
  { details: 'Irland', code: 'IE' },
  { details: 'Israel', code: 'IL' },
  { details: 'Man Insel', code: 'IM' },
  { details: 'Indien', code: 'IN' },
  { details: 'Brit.Geb.Ind.Oz', code: 'IO' },
  { details: 'Irak', code: 'IQ' },
  { details: 'Iran', code: 'IR' },
  { details: 'Island', code: 'IS' },
  { details: 'Italien', code: 'IT' },
  { details: 'Jersey', code: 'JE' },
  { details: 'Jamaika', code: 'JM' },
  { details: 'Jordanien', code: 'JO' },
  { details: 'Japan', code: 'JP' },
  { details: 'Kenia', code: 'KE' },
  { details: 'Kirgisistan', code: 'KG' },
  { details: 'Kambodscha', code: 'KH' },
  { details: 'Kiribati', code: 'KI' },
  { details: 'Komoren', code: 'KM' },
  { details: 'St.Kitts&Nevis', code: 'KN' },
  { details: 'Nordkorea', code: 'KP' },
  { details: 'Südkorea', code: 'KR' },
  { details: 'Kuwait', code: 'KW' },
  { details: 'Kaimaninseln', code: 'KY' },
  { details: 'Kasachstan', code: 'KZ' },
  { details: 'Laos', code: 'LA' },
  { details: 'Libanon', code: 'LB' },
  { details: 'St. Lucia', code: 'LC' },
  { details: 'Liechtenstein', code: 'LI' },
  { details: 'Sri Lanka', code: 'LK' },
  { details: 'Liberia', code: 'LR' },
  { details: 'Lesotho', code: 'LS' },
  { details: 'Litauen', code: 'LT' },
  { details: 'Luxemburg', code: 'LU' },
  { details: 'Lettland', code: 'LV' },
  { details: 'Libyen', code: 'LY' },
  { details: 'Marokko', code: 'MA' },
  { details: 'Monaco', code: 'MC' },
  { details: 'Moldau', code: 'MD' },
  { details: '', code: 'ME' },
  { details: '', code: 'MF' },
  { details: 'Madagaskar', code: 'MG' },
  { details: 'Marshall-Insel', code: 'MH' },
  { details: 'Nordmazedonien', code: 'MK' },
  { details: 'Mali', code: 'ML' },
  { details: 'Myanmar', code: 'MM' },
  { details: 'Mongolei', code: 'MN' },
  { details: 'Macau', code: 'MO' },
  { details: 'Nördl. Marianen', code: 'MP' },
  { details: 'Martinique', code: 'MQ' },
  { details: 'Mauretanien', code: 'MR' },
  { details: 'Montserrat', code: 'MS' },
  { details: 'Malta', code: 'MT' },
  { details: 'Mauritius', code: 'MU' },
  { details: 'Malediven', code: 'MV' },
  { details: 'Malawi', code: 'MW' },
  { details: 'Mexiko', code: 'MX' },
  { details: 'Malaysia', code: 'MY' },
  { details: 'Mosambik', code: 'MZ' },
  { details: 'Namibia', code: 'NA' },
  { details: 'Neukaledonien', code: 'NC' },
  { details: 'Niger', code: 'NE' },
  { details: 'Norfolkinseln', code: 'NF' },
  { details: 'Nigeria', code: 'NG' },
  { details: 'Nicaragua', code: 'NI' },
  { details: 'Niederlande', code: 'NL' },
  { details: 'Norwegen', code: 'NO' },
  { details: 'Nepal', code: 'NP' },
  { details: 'Nauru', code: 'NR' },
  { details: 'NATO', code: 'NT' },
  { details: 'Niue-Inseln', code: 'NU' },
  { details: 'Neuseeland', code: 'NZ' },
  { details: 'Oman', code: 'OM' },
  { details: 'Orange', code: 'OR' },
  { details: 'Panama', code: 'PA' },
  { details: 'Peru', code: 'PE' },
  { details: 'FranzPolynesien', code: 'PF' },
  { details: 'Papua-Neuguinea', code: 'PG' },
  { details: 'Philippinen', code: 'PH' },
  { details: 'Pakistan', code: 'PK' },
  { details: 'Polen', code: 'PL' },
  { details: 'StPier.,Miquel.', code: 'PM' },
  { details: 'Pitcairn Inseln', code: 'PN' },
  { details: 'Puerto Rico', code: 'PR' },
  { details: 'Palästina', code: 'PS' },
  { details: 'Portugal', code: 'PT' },
  { details: 'Palau', code: 'PW' },
  { details: 'Paraguay', code: 'PY' },
  { details: 'Katar', code: 'QA' },
  { details: 'Reunion', code: 'RE' },
  { details: 'Rumänien', code: 'RO' },
  { details: '', code: 'RS' },
  { details: 'Russische Foed.', code: 'RU' },
  { details: 'Ruanda', code: 'RW' },
  { details: 'Saudi-Arabien', code: 'SA' },
  { details: 'Salomonen', code: 'SB' },
  { details: 'Seychellen', code: 'SC' },
  { details: 'Sudan', code: 'SD' },
  { details: 'Schweden', code: 'SE' },
  { details: 'Singapur', code: 'SG' },
  { details: 'St. Helena', code: 'SH' },
  { details: 'Slowenien', code: 'SL' },
  { details: 'Svalbard', code: 'SJ' },
  { details: 'Slowakei', code: 'SK' },
  { details: 'Sierra Leone', code: 'SL' },
  { details: 'San Marino', code: 'SM' },
  { details: 'Senegal', code: 'SN' },
  { details: 'Somalia', code: 'SO' },
  { details: 'Suridetails', code: 'SR' },
  { details: 'Südsudan', code: 'SS' },
  { details: 'S.Tome,Principe', code: 'ST' },
  { details: 'El Salvador', code: 'SV' },
  { details: 'Sint Maarten', code: 'SX' },
  { details: 'Syrien', code: 'SY' },
  { details: 'Swasiland', code: 'SZ' },
  { details: 'Turks-,Caicosin', code: 'TC' },
  { details: 'Tschad', code: 'TD' },
  { details: 'French S.Territ', code: 'TF' },
  { details: 'Togo', code: 'TG' },
  { details: 'Thailand', code: 'TH' },
  { details: 'Tadschikistan', code: 'TJ' },
  { details: 'Tokelau-Inseln', code: 'TK' },
  { details: 'Osttimor', code: 'TL' },
  { details: 'Turkmenistan', code: 'TM' },
  { details: 'Tunesien', code: 'TN' },
  { details: 'Tonga', code: 'TO' },
  { details: 'Ost Timor', code: 'TP' },
  { details: 'Türkei', code: 'TR' },
  { details: 'Trinidad,Tobago', code: 'TT' },
  { details: 'Tuvalu', code: 'TV' },
  { details: 'Taiwan', code: 'TW' },
  { details: 'Tansania', code: 'TZ' },
  { details: 'Ukraine', code: 'UA' },
  { details: 'Uganda', code: 'UG' },
  { details: 'Minor Outl.Ins.', code: 'UM' },
  { details: 'Vereinigte Nat.', code: 'UN' },
  { details: 'USA', code: 'US' },
  { details: 'Uruguay', code: 'UY' },
  { details: 'Usbekistan', code: 'UZ' },
  { details: 'Vatikanstadt', code: 'VA' },
  { details: 'St. Vincent', code: 'VC' },
  { details: 'Venezuela', code: 'VE' },
  { details: 'Brit.Jungferni.', code: 'VG' },
  { details: 'Amer.Jungferni.', code: 'VI' },
  { details: 'Vietnam', code: 'VN' },
  { details: 'Vanuatu', code: 'VU' },
  { details: 'Wallis,Futuna', code: 'WF' },
  { details: 'Westsamoa', code: 'WS' },
  { details: 'Serbien', code: 'XS' },
  { details: 'Jemen', code: 'YE' },
  { details: 'Mayotte', code: 'YT' },
  { details: 'Südafrika', code: 'ZA' },
  { details: 'Sambia', code: 'ZM' },
  { details: 'Simbabwe', code: 'ZW' },

];



constructor() { }
}
